name: Build and Push Maven App Docker Image

on:
  push:
    branches: [ "master" ] # Trigger on pushes to the main branch
  # pull_request:
  #   branches: [ "main" ] # Optional: Trigger on pull requests to main (won't push)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read      # To checkout the code
      packages: write     # To push docker image to GHCR using GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Base image maven:3.6-jdk-8-slim is public, no special setup needed.

      - name: Set up QEMU # Optional: For multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # Use the default GITHUB_TOKEN for authentication with GHCR
          # within the same repository or organization.
          #username: ${{ github.actor }}
          #password: ${{ secrets.GITHUB_TOKEN }}
          # If GITHUB_TOKEN doesn't work (e.g., private repo, cross-org),
          # create a PAT with 'packages:write' scope and store it as a secret (e.g., GHCR_PAT)
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # --- OR ---

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }} # Create repository secret
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}    # Create repository secret (Access Token)

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Adjust image names as needed
          # For GHCR (lowercase username/org): Suggest adding '-app' or similar to distinguish
          #images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-app
          images: ghcr.io/acvatech/parent
          #images: ghcr.io/${{ github.repository_owner }}/parent
          # For Docker Hub:
          # images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-app

          # Define tags based on Git events
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha # Add Git SHA as a tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the current directory as context
          file: ./Dockerfile # Path to your Dockerfile (assuming it's in the root)
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # Only push on merge/push to main
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Enable build cache from GitHub Actions Cache
          cache-to: type=gha,mode=max # Enable writing cache to GitHub Actions Cache